import { StyleSheet } from 'react-native';
import { deviceHeight, deviceWidth, width } from './Dimensions';

export const searchButtonStyle = StyleSheet.create({
  button: {
    backgroundColor: '#FF7043',
    borderRadius: 30,
    padding: 8,
    maxWidth: deviceWidth / 3,
    minWidth: deviceWidth / 7,
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginTop: 3,
    height: deviceHeight * 0.045,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  disableButton: {
    backgroundColor: '#FF7043',
    borderRadius: 30,
    padding: 8,
    maxWidth: deviceWidth / 3,
    minWidth: deviceWidth / 7,
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginTop: 3,
    height: deviceHeight * 0.045,
    opacity: 0.6,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  text: {
    color: 'white',
    fontSize: deviceHeight * 0.017,
    textAlign: 'center',
  },
  resetButton: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: deviceHeight * 0.023,
    width: deviceWidth * 0.052,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: deviceWidth * 0.001,
    marginTop: -deviceHeight * 0.01,
    right: width * 0.0351,
    overflow: 'visible',
  },
  resolutionButtonReset: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: deviceHeight * 0.023,
    width: deviceWidth * 0.052,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    // marginLeft: width * 0.15,
    // marginTop: -height * 0.062,
    overflow: 'visible',
    top: -deviceHeight * 0.0652,
    left: deviceWidth * 0.245,
  },
  meterResetButton: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: deviceHeight * 0.023,
    width: deviceWidth * 0.052,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    // marginLeft: width * 0.17,
    // marginTop: -height * 0.062,
    // top: -height * 0.0025,
    // left: width * 0.025,
    top: -deviceHeight * 0.04,
    left: deviceWidth * 0.1,
    overflow: 'visible',
  },
  yearResetButton: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: deviceHeight * 0.023,
    width: deviceHeight * 0.025,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    // marginLeft: width * 0.155,
    // marginTop: -height * 0.06,
    top: -deviceHeight * 0.055,
    left: deviceWidth * 0.075,
    overflow: 'visible',
  },
});
