import { StyleSheet } from 'react-native';
import { deviceHeight, deviceWidth, height, width } from './Dimensions';

export const searchButtonStyle = StyleSheet.create({
  button: {
    backgroundColor: '#FF7043',
    borderRadius: 30,
    padding: 8,
    maxWidth: width / 3,
    minWidth: width / 7,
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginTop: 14,
    height: 40,
    // flexDirection: 'row',
    justifyContent: 'center',
  },
  disableButton: {
    backgroundColor: '#FF7043',
    borderRadius: 30,
    padding: 8,
    maxWidth: width / 3,
    minWidth: width / 7,
    alignSelf: 'flex-end',
    alignItems: 'center',
    marginTop: 3,
    height: 40,
    opacity: 0.6,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  text: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
  },
  resetButton: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: height * 0.023,
    width: width * 0.052,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: -17,
    marginTop: -12,
    overflow: 'visible',
  },
  resolutionButtonReset: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: height * 0.023,
    width: width * 0.052,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: width * 0.27,
    marginTop: -height * 0.062,
    overflow: 'visible',
  },
  meterResetButton: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: deviceHeight * 0.023,
    width: deviceWidth * 0.047,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: deviceWidth * 0.18,
    marginTop: -deviceHeight * 0.162,
    overflow: 'visible',
  },
  yearResetButton: {
    borderWidth: 0.5,
    borderColor: '#dfdfdf',
    backgroundColor: '#f2f2f2',
    height: deviceHeight * 0.023,
    width: deviceWidth * 0.047,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: deviceWidth * 0.12,
    marginTop: -deviceHeight * 0.062,
    overflow: 'visible',
  },
});
