export const mockedPremises = [
  { premiseId: 1, designation: 'A1', name: 'Premise One' },
  { premiseId: 2, designation: 'A2', name: 'Premise Two' },
  { premiseId: 3, designation: 'A3', name: 'Premise Three' },
  { premiseId: 4, designation: 'A4', name: 'Premise Four' },
  { premiseId: 5, designation: 'A5', name: 'Premise Five' },
  { premiseId: 6, designation: 'B1', name: 'Premise Six' },
  { premiseId: 7, designation: 'B2', name: 'Premise Seven' },
  { premiseId: 8, designation: 'B3', name: 'Premise Eight' },
  { premiseId: 9, designation: 'B4', name: 'Premise Nine' },
  { premiseId: 10, designation: 'B5', name: 'Premise Ten' },
  { premiseId: 11, designation: 'C1', name: 'Premise Eleven' },
  { premiseId: 12, designation: 'C2', name: 'Premise Twelve' },
  { premiseId: 13, designation: 'C3', name: 'Premise Thirteen' },
  { premiseId: 14, designation: 'C4', name: 'Premise Fourteen' },
  { premiseId: 15, designation: 'C5', name: 'Premise Fifteen' },
  { premiseId: 16, designation: 'D1', name: 'Premise Sixteen' },
  { premiseId: 17, designation: 'D2', name: 'Premise Seventeen' },
  { premiseId: 18, designation: 'D3', name: 'Premise Eighteen' },
  { premiseId: 19, designation: 'D4', name: 'Premise Nineteen' },
  { premiseId: 20, designation: 'D5', name: 'Premise Twenty' },
];
