import { Product } from '../Types/Interfaces/Type';

export const mockedData: Product[] = [
  { Id: 25, Code: 'FJV', Unit: 'kWh' },
  { Id: 26, Code: 'El', Unit: 'kWh' },
  { Id: 27, Code: 'FJK', Unit: 'kWh' },
  { Id: 28, Code: 'VAT', Unit: 'm³' },
  { Id: 29, Code: 'Effekt', Unit: 'kW' },
  { Id: 30, Code: 'Flöde', Unit: 'm³/h' },
  { Id: 31, Code: 'TMP', Unit: '°C' },
  { Id: 32, Code: 'TMP', Unit: '°C' },
  { Id: 33, Code: 'VOL', Unit: 'm³' },
  { Id: 63, Code: 'FJV sek', Unit: 'kWh' },
  { Id: 64, Code: 'EL sek', Unit: 'kWh' },
  { Id: 65, Code: 'FJK sek', Unit: 'kWh' },
  { Id: 66, Code: 'VAT sek', Unit: 'm³' },
  { Id: 67, Code: 'FJV under', Unit: 'kWh' },
  { Id: 68, Code: 'EL under', Unit: 'kWh' },
  { Id: 69, Code: 'FJK under', Unit: 'kWh' },
  { Id: 70, Code: 'VAT under', Unit: 'm³' },
  { Id: 426, Code: 'VAT ind', Unit: 'm³' },
  { Id: 449, Code: 'EL prod', Unit: 'kWh' },
  { Id: 476, Code: 'Prod värme', Unit: 'kWh' },
  { Id: 477, Code: 'FJV Effekt', Unit: 'kW' },
  { Id: 478, Code: 'El Effekt', Unit: 'kW' },
  { Id: 484, Code: 'Proc VAT', Unit: 'm³' },
];
